---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rouser
  namespace: default
---
apiVersion: v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
  name: rouser-read-only
rules:
- apiGroups:
  - ""
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: v1
metadata:
  name: rouser-read-only
subjects:
- kind: ServiceAccount
  name: rouser
  namespace: default
roleRef:
  kind: ClusterRole
  name: rouser-read-only
  apiGroup: v1
